image: node

stages:
  - build
  - test

build: 
  stage: build
  script:
    - echo "Building"
    - npm install
  artifacts: # way to preserve installation between stages
    paths:
      - node_modules
    
test:
  stage: test
  script: 
    #- npm install
    - echo "Testing..."
    - npm run test
  tags: 
    - docker